blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/cjvana/frequency-scanner/discussions
    about: Ask questions and discuss ideas with the community
  - name: TinySA Community
    url: https://groups.io/g/tinysa
    about: For TinySA hardware questions not related to this software
